### ISSUE TITLE
How to obtain 512 bits with PKCS1v15?

### ISSUE THREAD

**Issue by evso9816** [Yubico/python-yubihsm#9]
I have been trying to hash and sign 512 bits using PKCS1v15, but the result is more than 512. 
RSA offers 2048, 3072, and 4096 bits key for PKCSv15. How may I play around to obtain 512 bits?

However, with the same program, hashing and signing for 512 using ECDSA works perfectly.

Can Yubico PKCS1v15 provide exactly 512 bit?

Thank you.

Eva

**Comment by joernheissler** [comment]
Hi evso9816,
RSA signatures are as large as the RSA modulus. If you want a 512 bit signature, you need to use an RSA 512 key.
According to https://developers.yubico.com/YubiHSM2/Concepts/Algorithms.html and your own comment, RSA 512 is not supported.
So it's not possible. RSA 512 is insecure anyway, so there's no good reason to support it.

Your issue is a year old. Did you figure things out by now, can the ticket be resolved?

**Comment by evso9816** [comment]
Yes, keep the case closed. I solved it.
Thanks!

**Comment by nevun** [comment]
thanks :+1:
